// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZe6edAdhwn05UaB0xP37WAtPxyiXpicw',
    appId: '1:588005836404:web:93d24e54b1c6ea11c4b321',
    messagingSenderId: '588005836404',
    projectId: 'sispol-7-913ef',
    authDomain: 'sispol-7-913ef.firebaseapp.com',
    databaseURL: 'https://sispol-7-913ef-default-rtdb.firebaseio.com',
    storageBucket: 'sispol-7-913ef.appspot.com',
    measurementId: 'G-K6VRDBZXWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_vFE0GqbrR9Gt9olXI79VWrt3QjHoXno',
    appId: '1:588005836404:android:2fc85513363a443ec4b321',
    messagingSenderId: '588005836404',
    projectId: 'sispol-7-913ef',
    databaseURL: 'https://sispol-7-913ef-default-rtdb.firebaseio.com',
    storageBucket: 'sispol-7-913ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQbBrxa2f4L9OnkfIJ4B0jl1VBXd7TCw',
    appId: '1:588005836404:ios:61bb5e2f5256c607c4b321',
    messagingSenderId: '588005836404',
    projectId: 'sispol-7-913ef',
    databaseURL: 'https://sispol-7-913ef-default-rtdb.firebaseio.com',
    storageBucket: 'sispol-7-913ef.appspot.com',
    iosBundleId: 'com.example.sispol7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQbBrxa2f4L9OnkfIJ4B0jl1VBXd7TCw',
    appId: '1:588005836404:ios:61bb5e2f5256c607c4b321',
    messagingSenderId: '588005836404',
    projectId: 'sispol-7-913ef',
    databaseURL: 'https://sispol-7-913ef-default-rtdb.firebaseio.com',
    storageBucket: 'sispol-7-913ef.appspot.com',
    iosBundleId: 'com.example.sispol7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZe6edAdhwn05UaB0xP37WAtPxyiXpicw',
    appId: '1:588005836404:web:93d24e54b1c6ea11c4b321',
    messagingSenderId: '588005836404',
    projectId: 'sispol-7-913ef',
    authDomain: 'sispol-7-913ef.firebaseapp.com',
    databaseURL: 'https://sispol-7-913ef-default-rtdb.firebaseio.com',
    storageBucket: 'sispol-7-913ef.appspot.com',
    measurementId: 'G-K6VRDBZXWD',
  );

}